### ISSUE TITLE
PR

### ISSUE THREAD

**Issue by synicalsyntax** [zulipbot-testing/synicalsyntax#24]
pr

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-emoji members, this issue needs your attention!

**Comment by zulipbot-test** [comment]
**Error:** Label "derp" does not exist and was thus not added to this issue.

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-user-docs members, this issue was labeled with the **area: documentation (user)** label, so you may want to check it out!

**Comment by zulipbot-test** [comment]
**Error:** Label "derp" does not exist and was thus not added to this issue.

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-emoji members, this issue was labeled with the **area: emoji** label, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-emoji members, this issue was labeled with the **area: emoji** label, so you may want to check it out!

**Comment by synicalsyntax** [comment]
@zulipbot abandon

**Comment by synicalsyntax** [comment]
@zulipbot remove "area: emoji"

**Comment by synicalsyntax** [comment]
@zulipbot label "bug"

**Comment by synicalsyntax** [comment]
@zulipbot label "bug"

**Comment by synicalsyntax** [comment]
@zulipbot label "buggo"

**Comment by zulipbot-test** [comment]
**Error:** Label "buggo" does not exist and was thus not added to this issue.

**Comment by synicalsyntax** [comment]
@zulipbot abandon

**Comment by zulipbot-test** [comment]
Congratulations, @synicaltests, you've successfully claimed your first issue! Since you're a new contributor, you now have pull (read-only) access to this repository.

Please review our [code contribution guidelines](http://zulip.readthedocs.io/en/latest/index.html#code-docs) and sign the [Dropbox Contributor License Agreement](https://opensource.dropbox.com/cla/) before opening any pull requests for any issues that you're working on.

Also, if you haven't done so already, please join us on the Zulip development server at [chat.zulip.org](https://chat.zulip.org/)! Our community of developers use **chat.zulip.org** as our primary communication forum for developing Zulip; you can read more about the **chat.zulip.org** community in our [documentation](http://zulip.readthedocs.io/en/latest/chat-zulip-org.html).

**Note:** Depending on your [notification settings](https://github.com/settings/notifications), granting you the permission in GitHub's model that allows you to be assigned issues by **zulipbot** may result in making you a "watcher" on this repository, which means that you'll get notifications for every issue and pull request in this repository; for a large repository like [zulip/zulip](https://github.com/zulip/zulip), that means receiving over 100 emails per day. If you don't want to receive notifications unless you're actually involved with the issue (which is usually the right choice for large projects), you should [unwatch this repository](https://help.github.com/articles/unwatching-repositories/).

**Comment by zulipbot-test** [comment]
Congratulations, @synicaltests, you've successfully claimed your first issue! Since you're a new contributor, you now have pull (read-only) access to this repository.

Please review our [code contribution guidelines](http://zulip.readthedocs.io/en/latest/index.html#code-docs) and sign the [Dropbox Contributor License Agreement](https://opensource.dropbox.com/cla/) before opening any pull requests for any issues that you're working on.

Also, if you haven't done so already, please join us on the Zulip development server at [chat.zulip.org](https://chat.zulip.org/)! Our community of developers use **chat.zulip.org** as our primary communication forum for developing Zulip; you can read more about the **chat.zulip.org** community in our [documentation](http://zulip.readthedocs.io/en/latest/chat-zulip-org.html).

**Note:** Depending on your [notification settings](https://github.com/settings/notifications), granting you the permission in GitHub's model that allows you to be assigned issues by **zulipbot** may result in making you a "watcher" on this repository, which means that you'll get notifications for every issue and pull request in this repository; for a large repository like [zulip/zulip](https://github.com/zulip/zulip), that means receiving over 100 emails per day. If you don't want to receive notifications unless you're actually involved with the issue (which is usually the right choice for large projects), you should [unwatch this repository](https://help.github.com/articles/unwatching-repositories/).

**Comment by synicalsyntax** [comment]
@zulipbot label "enhancement"
