### ISSUE TITLE
config

### ISSUE THREAD

**Issue by synicalsyntax** [zulipbot-testing/synicalsyntax#55]
@zulipbot-test label "area: documentation (developer)"

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-development members, this issue was labeled with the **area: documentation (developer)** label, so you may want to check it out!

**Comment by synicalsyntax** [comment]
@zulipbot-test claim @zulipbot-test label "bug" "enhancement @zulipbot-test remove "area: documentation (developer)" "bug"

**Comment by synicalsyntax** [comment]
@zulipbot-test claim @zulipbot-test label "bug" "enhancement" @zulipbot-test remove "area: documentation (developer)" "bug"

**Comment by synicalsyntax** [comment]
@zulipbot-test remove "area: documentation (developer)" "bug"

**Comment by synicalsyntax** [comment]
@zulipbot-test label "bug" "enhancement" @zulipbot-test remove "area: documentation (developer)" "bug"

**Comment by zulipbot-test** [comment]
**Error:** Label "enhancement" already exists and was thus not added again to this issue.

**Comment by synicalsyntax** [comment]
@zulipbot-test remove "area: documentation (developer)" "bug" @zulipbot-test label "bug" "enhancement"

**Comment by zulipbot-test** [comment]
**Error:** Label "area: documentation (developer)" does not exist and was thus not removed from this issue.

**Comment by synicalsyntax** [comment]
@zulipbot-test claim @zulipbot-test unclaim

**Comment by synicalsyntax** [comment]
@zulipbot-test unclaim

**Comment by synicalsyntax** [comment]
@zulipbot-test claim @zulipbot-test unclaim

**Comment by synicalsyntax** [comment]
@zulipbot-test claim @zulipbot-test unclaim

**Comment by synicalsyntax** [comment]
@zulipbot-test claim @zulipbot-test unclaim

**Comment by synicalsyntax** [comment]
@zulipbot-test label "bug" "enhancement" @zulipbot-test remove "area: documentation (developer)" "bug"

**Comment by zulipbot-test** [comment]
**Error:** Label "enhancement" already exists and was thus not added again to this issue.

**Comment by synicalsyntax** [comment]
@zulipbot-test label "bug" "enhancement" @zulipbot-test remove "area: documentation (developer)" "bug"

**Comment by zulipbot-test** [comment]
**Error:** Label "area: documentation (developer)" does not exist and was thus not removed from this issue.

**Comment by zulipbot-test** [comment]
**Error:** Labels "bug", "enhancement" already exist and were thus not added again to this issue.

**Comment by synicalsyntax** [comment]
@zulipbot-test label "bug" "enhancement" @zulipbot-test remove "area: documentation (developer)" "bug"

**Comment by zulipbot-test** [comment]
**Error:** Labels "area: documentation (developer)", "bug" do not exist and were thus not removed from this issue.

**Comment by zulipbot-test** [comment]
**Error:** Label "enhancement" already exists and was thus not added again to this issue.

**Comment by zulipbot-test** [comment]
**Error:** Label "area: documentation (developer)" does not exist and was thus not removed from this issue.

**Comment by zulipbot-test** [comment]
**Error:** Label "bug" already exists and was thus not added again to this issue.

**Comment by synicaltests** [comment]
Hello @synicalsyntax, you claimed this issue to work on it, but this issue and any referenced pull requests haven't been updated for a week. Are you still working on this issue?

If so, please update this issue by leaving a comment on this issue to let me know that you're still working on it. Otherwise, I'll automatically remove you from this issue in 3 days.

If you've decided to work on something else, simply comment `@zulipbot abandon` so that someone else can claim it and continue from where you left off.

Thank you for your valuable contributions to Zulip!

**Comment by synicaltests** [comment]
Hello @synicalsyntax, you claimed this issue to work on it, but this issue and any referenced pull requests haven't been updated for a week. Are you still working on this issue?

If so, please update this issue by leaving a comment on this issue to let me know that you're still working on it. Otherwise, I'll automatically remove you from this issue in 3 days.

If you've decided to work on something else, simply comment `@zulipbot abandon` so that someone else can claim it and continue from where you left off.

Thank you for your valuable contributions to Zulip!

**Comment by synicaltests** [comment]
Hello @synicalsyntax, you claimed this issue to work on it, but this issue and any referenced pull requests haven't been updated for a week. Are you still working on this issue?

If so, please update this issue by leaving a comment on this issue to let me know that you're still working on it. Otherwise, I'll automatically remove you from this issue in 3 days.

If you've decided to work on something else, simply comment `@zulipbot abandon` so that someone else can claim it and continue from where you left off.

Thank you for your valuable contributions to Zulip!

**Comment by synicaltests** [comment]
Hello @synicalsyntax, you claimed this issue to work on it, but this issue and any referenced pull requests haven't been updated for a week. Are you still working on this issue?

If so, please update this issue by leaving a comment on this issue to let me know that you're still working on it. Otherwise, I'll automatically remove you from this issue in 3 days.

If you've decided to work on something else, simply comment `@zulipbot abandon` so that someone else can claim it and continue from where you left off.

Thank you for your valuable contributions to Zulip!

**Comment by synicaltests** [comment]
Hello @synicalsyntax, you claimed this issue to work on it, but this issue and any referenced pull requests haven't been updated for a week. Are you still working on this issue?

If so, please update this issue by leaving a comment on this issue to let me know that you're still working on it. Otherwise, I'll automatically remove you from this issue in 3 days.

If you've decided to work on something else, simply comment `@zulipbot abandon` so that someone else can claim it and continue from where you left off.

Thank you for your valuable contributions to Zulip!

**Comment by synicaltests** [comment]
Hello @synicalsyntax, you claimed this issue to work on it, but this issue and any referenced pull requests haven't been updated for a week. Are you still working on this issue?

If so, please update this issue by leaving a comment on this issue to let me know that you're still working on it. Otherwise, I'll automatically remove you from this issue in 3 days.

If you've decided to work on something else, simply comment `@zulipbot abandon` so that someone else can claim it and continue from where you left off.

Thank you for your valuable contributions to Zulip!

**Comment by synicaltests** [comment]
Hello @synicalsyntax, you claimed this issue to work on it, but this issue and any referenced pull requests haven't been updated for a week. Are you still working on this issue?

If so, please update this issue by leaving a comment on this issue to let me know that you're still working on it. Otherwise, I'll automatically remove you from this issue in 3 days.

If you've decided to work on something else, simply comment `@zulipbot abandon` so that someone else can claim it and continue from where you left off.

Thank you for your valuable contributions to Zulip!

**Comment by synicaltests** [comment]
Hello @synicalsyntax, you claimed this issue to work on it, but this issue and any referenced pull requests haven't been updated for a week. Are you still working on this issue?

If so, please update this issue by leaving a comment on this issue to let me know that you're still working on it. Otherwise, I'll automatically remove you from this issue in 3 days.

If you've decided to work on something else, simply comment `@zulipbot abandon` so that someone else can claim it and continue from where you left off.

Thank you for your valuable contributions to Zulip!

**Comment by synicaltests** [comment]
Hello @synicalsyntax, you claimed this issue to work on it, but this issue and any referenced pull requests haven't been updated for a week. Are you still working on this issue?

If so, please update this issue by leaving a comment on this issue to let me know that you're still working on it. Otherwise, I'll automatically remove you from this issue in 3 days.

If you've decided to work on something else, simply comment `@zulipbot abandon` so that someone else can claim it and continue from where you left off.

Thank you for your valuable contributions to Zulip!

**Comment by synicaltests** [comment]
Hello @synicalsyntax, you claimed this issue to work on it, but this issue and any referenced pull requests haven't been updated for a week. Are you still working on this issue?

If so, please update this issue by leaving a comment on this issue to let me know that you're still working on it. Otherwise, I'll automatically remove you from this issue in 3 days.

If you've decided to work on something else, simply comment `@zulipbot abandon` so that someone else can claim it and continue from where you left off.

Thank you for your valuable contributions to Zulip!

**Comment by synicaltests** [comment]
Hello @synicalsyntax, you claimed this issue to work on it, but this issue and any referenced pull requests haven't been updated for a week. Are you still working on this issue?

If so, please update this issue by leaving a comment on this issue to let me know that you're still working on it. Otherwise, I'll automatically remove you from this issue in 3 days.

If you've decided to work on something else, simply comment `@zulipbot abandon` so that someone else can claim it and continue from where you left off.

Thank you for your valuable contributions to Zulip!

**Comment by synicaltests** [comment]
Hello @synicalsyntax, you claimed this issue to work on it, but this issue and any referenced pull requests haven't been updated for a week. Are you still working on this issue?

If so, please update this issue by leaving a comment on this issue to let me know that you're still working on it. Otherwise, I'll automatically remove you from this issue in 3 days.

If you've decided to work on something else, simply comment `@zulipbot abandon` so that someone else can claim it and continue from where you left off.

Thank you for your valuable contributions to Zulip!

**Comment by synicalsyntax** [comment]
@synicaltests claim

**Comment by synicalsyntax** [comment]
@zulipbot-test claim

**Comment by synicaltests** [comment]
Hello @synicalsyntax, you claimed this issue to work on it, but this issue and any referenced pull requests haven't been updated for a week. Are you still working on this issue?

If so, please update this issue by leaving a comment on this issue to let me know that you're still working on it. Otherwise, I'll automatically remove you from this issue in 3 days.

If you've decided to work on something else, simply comment `@zulipbot abandon` so that someone else can claim it and continue from where you left off.

Thank you for your valuable contributions to Zulip!
